name: todoapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  logger: ^1.3.0
  flutter_svg: ^2.0.5
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^4.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/.env
    - assets/icons/
    - assets/images/
    - assets/datas/

  fonts:
    - family: mikhak_medium
      fonts:
        - asset: assets/fonts/mikhak_medium.ttf

    - family:  montserrat_black
      fonts:
        - asset: assets/fonts/montserrat_black.ttf

    - family:  montserrat_bold
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf

    - family:  montserrat_extra_light
      fonts:
        - asset: assets/fonts/montserrat_extra_light.ttf

    - family:  montserrat_light
      fonts:
        - asset: assets/fonts/montserrat_light.ttf

    - family:  montserrat_medium
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf

    - family: montserrat_regular
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf

    - family:  montserrat_extra_bold
      fonts:
        - asset: assets/fonts/montserrat_extra_bold.ttf

    - family:  montserrat_semi_bold
      fonts:
        - asset: assets/fonts/montserrat_semi_bold.ttf

    - family:  montserrat_thin
      fonts:
        - asset: assets/fonts/montserrat_thin.ttf
